### PR TITLE
🅱️akes a 🅱️ig 🅱️ on 🅱️lue

### PR DESCRIPTION
**Pull request by Eiim**
I got it. Ended up 🅱️eing simpler than expected.

### CODE REVIEW

**Comment by Eiim** [comment]
Don't change CNAME, btw

**Comment by pognog69** [comment]
Going to merge this soon, hope I don't 🅱️reak anything

**Comment by pognog69** [comment]
it did 🅱️reak something why is it a 404 now

**Comment by pognog69** [comment]
never mind i'm just im🅱️atient

**Comment by Eiim** [comment]
alright 🅱️ool

**Pull request merged**
